### ISSUE TITLE
Макеты UI

### ISSUE THREAD

**Issue by maikleProko** [moevm/mse1h2024-clock-ml#1]
Необходимо сделать макеты приложения в соответствии с описанием в постановке задачи. Оформить в разделе Wiki

**Comment by tapekhav** [comment]
https://github.com/moevm/mse1h2024-clock-ml/wiki/%D0%9C%D0%B0%D0%BA%D0%B5%D1%82-UI

**Comment by maikleProko** [comment]
Надо поправить надписи:
- при переходе со страницы приветствия на страницу тестированием ("Пользователь переходит на ..." -> "Переход на ..." )
- при переходе со страницы тестирования на окно загрузки ("Пользователя перебрасывает на ..." -> "Переброс на ..." )
