### ISSUE TITLE
Представление каждого сервиса docker контейнером

### ISSUE THREAD

**Issue by maikleProko** [moevm/mse1h2024-clock-ml#12]

**Comment by AlexanderKamynin** [comment]
Docker: https://github.com/moevm/mse1h2024-clock-ml/pull/16

**Comment by ormequ** [comment]
Dockerfile для backend: https://github.com/moevm/mse1h2024-clock-ml/pull/15
Docker-compose напишу после того, как фронт+бэк+ml будут в мэйне
