### ISSUE TITLE
Связывание ML-сервиса и бекенда через RabbitMQ

### ISSUE THREAD

**Issue by ormequ** [moevm/mse1h2024-clock-ml#25]
В текущем варианте работает связь через REST API. Необходимо сделать работу также через RabbitMQ по аналогичной схеме: отправка картинки -> получение количества баллов

**Comment by ormequ** [comment]
заодно надо переделать Content-Type на формдату

**Comment by AlexanderKamynin** [comment]
> заодно надо переделать Content-Type на формдату

В таком случае, @tapekhav жду от тебя тоже формдату с временем

**Comment by tapekhav** [comment]
Так, я не понял, кто мой тиммейте в итоге @ormequ или @AlexanderKamynin

**Comment by AlexanderKamynin** [comment]
> Так, я не понял, кто мой тиммейте в итоге @ormequ или @AlexanderKamynin 

На Илье это единственное issue, поэтому думаю, что в приоритете он. Я могу код поревьювить, если хотите 🤭🤔

**Comment by ormequ** [comment]
Будем опираться на https://habr.com/ru/articles/747644/
