### ISSUE TITLE
Ошибка CORS политики при использовании Chrome

### ISSUE THREAD

**Issue by maikleProko** [moevm/mse1h2024-clock-ml#54]
При отправке запроса между пользовательским интерфейсом и сервером с chrome происходит ошибка CORS политики, с Firefox все работает нормально

**Comment by ormequ** [comment]
Мне не удается воспроизвести ошибку

**Comment by tapekhav** [comment]
Посмотрел бэк, вроде бы, там все ок. Ошибок с cors не должно быть.
